name: tfaction apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private_key: ${{ secrets.TFACTION_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.56.5
          working_directory: aqua
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: List targets
        id: list-targets
        uses: suzuki-shunsuke/tfaction/list-targets@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

  apply:
    needs: setup
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
      TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
      TFACTION_IS_APPLY: "true"
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private_key: ${{ secrets.TFACTION_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.56.5
          working_directory: aqua
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup tfaction
        uses: suzuki-shunsuke/tfaction/setup@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Apply
        uses: suzuki-shunsuke/tfaction/apply@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
