name: tfaction plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private_key: ${{ secrets.TFACTION_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.36.1
          working_directory: aqua

      - name: List targets
        id: list-targets
        uses: suzuki-shunsuke/tfaction/list-targets@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

  plan:
    needs: setup
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target }}
      TFACTION_IS_APPLY: "false"
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private_key: ${{ secrets.TFACTION_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.36.1
          working_directory: aqua

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup tfaction
        uses: suzuki-shunsuke/tfaction/setup@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Test
        uses: suzuki-shunsuke/tfaction/test@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Plan
        uses: suzuki-shunsuke/tfaction/plan@v1.20.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
